# K3s docs: https://docs.k3s.io/
# Run playbook: ansible-playbook -i inventory.yaml k3s/setup.yaml

- name: Setup K3s
  gather_facts: true
  hosts: k3s
  vars:
    k3s_version: 1.37.0
    #k3s_node_type: server # possible values: [server, agent]; should be defined on host level inside inventory;
    #k3s_master_node: false # Set this to true, on the node which should initialize the cluster + store the join token

  tasks:
    # - name: Get current index
    #   ansible.builtin.set_fact:
    #     host_index: "{{ ansible_play_hosts.index(inventory_hostname) }}"

    - name: Get K3s cluster join token
      ansible.builtin.command:
        cmd: cat /var/lib/rancher/k3s/server/token
      become: true
      run_once: true
      when: k3s_master_node
      register: join_token
      changed_when: false
      failed_when: false

    - name: Save join token as fact
      ansible.builtin.set_fact:
        k3s_join_token: "{{ join_token.stdout }}"
        k3s_join_url: "https://{{ ansible_host }}:6443" # get URL to join the cluster (ip of the master node)
      run_once: true
      when: k3s_master_node

    - name: Install kernel-modules-extra on RHEL-based-oses
      ansible.builtin.dnf:
        name: "kernel-modules-extra"
        state: present
      become: true
      when: ansible_os_family == 'RedHat'
      register: kernel_modules

    - name: Reboot if kernel modules were installed
      ansible.builtin.reboot:
      become: true
      when: kernel_modules.changed

    - name: Disable firewalld.service # as recommended by K3s: https://docs.k3s.io/installation/requirements?os=rhel#firewalld-1
      ansible.builtin.systemd_service:
        enabled: false
        name: firewalld.service
        state: stopped
      become: true
      when: ansible_os_family == 'RedHat'
      ignore_errors: true # Skips step if firewalld isn't installed

    - name: Download K3s binary
      ansible.builtin.get_url:
        #checksum:
        dest: /usr/local/bin/k3s
        mode: "a+x"
        url: "https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}+k3s1/k3s"
      become: true

    - name: Create symlinks for additional commands
      ansible.builtin.file:
        force: true
        path: "{{ item }}"
        src: /usr/local/bin/k3s
        state: link
      become: true
      loop:
        - /usr/local/bin/kubectl
        - /usr/local/bin/crictl
        - /usr/local/bin/ctr

    - name: Create systemd unit for K3s
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service
        mode: '755'
        src: ./systemd/k3s.service.j2
      become: true

    - name: Create env file for K3s
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service.env
        mode: '600'
        src: ./systemd/k3s.service.env.j2
      become: true

    - name: Enable & start K3s service
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        name: k3s.service
        state: started
      become: true