# K3s docs: https://docs.k3s.io/
# Run playbook: ansible-playbook -i inventory.yaml k3s/setup.yaml

- name: Setup K3s
  gather_facts: true
  hosts: k3s
  vars:
    # --- GLOBAL K3S OPTIONS ---
    k3s_version: 1.37.0                     # [Required] Which version of K3s should be installed; see https://github.com/k3s-io/k3s/releases

    # --- CLUSTER SPECIFIC OPTIONS (should be defined in inventory) ---
    #k3s_fixed_registration_address: ""     # [Optional] Fixed registration address behind Load Balancer, Virtual IP or DNS record for TLS SAN (Subject Alternative Name)

    # --- NODE SPECIFIC OPTIONS (should be defined in inventory) ---
    #k3s_node_type: server                  # [Required] Role of the node: 'server' or 'agent'
    #k3s_master_node: false                 # [Optional] Set to true, on the node which should initialize the cluster + store the join token. Should only be set on one node.

  tasks:
    # STEP 1 - PREPARE ALL NODES
    - name: Install kernel-modules-extra on RHEL-based-oses
      ansible.builtin.dnf:
        name: "kernel-modules-extra"
        state: present
      become: true
      when: ansible_os_family == 'RedHat'
      register: kernel_modules

    - name: Reboot if kernel modules were installed
      ansible.builtin.reboot:
      become: true
      when: kernel_modules.changed

    - name: Disable firewalld.service # as recommended by K3s: https://docs.k3s.io/installation/requirements?os=rhel#firewalld-1
      ansible.builtin.systemd_service:
        enabled: false
        name: firewalld.service
        state: stopped
      become: true
      when: ansible_os_family == 'RedHat'
      ignore_errors: true # Skips step if firewalld isn't installed

    - name: Download K3s binary
      ansible.builtin.get_url:
        #checksum:
        dest: /usr/local/bin/k3s
        mode: "a+x"
        url: "https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}+k3s1/k3s"
      become: true

    - name: Create symlinks for additional commands
      ansible.builtin.file:
        force: true
        path: "{{ item }}"
        src: /usr/local/bin/k3s
        state: link
      become: true
      loop:
        - /usr/local/bin/kubectl
        - /usr/local/bin/crictl
        - /usr/local/bin/ctr

    - name: Create systemd unit for K3s
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service
        mode: '755'
        src: ./systemd/k3s.service.j2
      become: true

    # STEP 2 - SETUP MASTER NODE / INIT CLUSTER
    - name: Create env file for K3s (only master)
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service.env
        mode: '600'
        src: ./systemd/k3s.service.env.j2
      become: true
      when: k3s_master_node

    - name: Enable & start K3s service (only master)
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        name: k3s.service
        state: started
      become: true
      when: k3s_master_node

    # STEP 3 - GET JOIN TOKEN
    - name: Wait for generation of join token
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/token
        state: "present"
      become: true
      when: k3s_master_node

    - name: Get K3s cluster join token
      ansible.builtin.command:
        cmd: cat /var/lib/rancher/k3s/server/token
      become: true
      when: k3s_master_node
      register: join_token
      changed_when: false

    - name: Save join token + URL as fact
      ansible.builtin.set_fact:
        k3s_join_token: >- # get join token
          {% for host in ansible_play_hosts %}
          {% if hostvars[host].k3s_master_node | default(false) %}
          {{ hostvars[host].join_token.stdout | trim }}
          {% endif %}
          {% endfor %}
        k3s_join_url: >- # get URL to join the cluster (ip of the master node)
          {% if k3s_node_type == 'agent' and k3s_fixed_registration_address | default(false) %}
          {{ k3s_fixed_registration_address }}
          {% else %}
            {% for host in ansible_play_hosts %}
              {% if hostvars[host].k3s_master_node | default(false) %}
              https://{{ hostvars[host].ansible_host }}:6443
              {% endif %}
            {% endfor %}
          {% endif %}
    
    # STEP 4 - JOIN NODES
    - name: Create env file for K3s
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service.env
        mode: '600'
        src: ./systemd/k3s.service.env.j2
      become: true
      when: not k3s_master_node

    - name: Enable & start K3s service
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        name: k3s.service
        state: started
      become: true
      when: not k3s_master_node