# OpenZiti docs: https://netfoundry.io/docs/openziti/intro
# Run playbook: ansible-playbook -i inventory.yaml openziti/baremetal-tunneler.yaml

- name: Install OpenZiti tunneler locally (bare-metal)
  gather_facts: true
  hosts:
    - debian-ziti-test
  vars:
    # --- DEBIAN TO UBUNTU LTS VERSION MAPPING ---
    ubuntu_lts_mapping:                                # [Required for Debian] Map debian version names to it's ubuntu LTS pendant; as shown here: https://netfoundry.io/docs/openziti/how-to-guides/tunnelers/linux/debian-package/
      trixie: "jammy"
      bookworm: "jammy"
      bullseye: "focal"

    # --- OPENZITI TUNNELER OPTIONS ---
    ziti_identity_dir: /opt/openziti/etc/identities     # [Required] The directory where ziti-edge-tunnel stores it's identities.
    #ziti_identity_name: my_identity                    # [Optional] How the file of the imported identiy should be called. Defaults to ansible_hostname.
    #ziti_use_systemd_resolved: false                   # [Optional] Defines wether to configure systemd-resolved with ziti-edge-tunnel as DNS resolver or not. Defaults to false.

  tasks:
    # STEP 1 - INSTALL + SETUP OPENZITI TUNNELER (ziti-edge-tunnel)
    - name: Map UBUNTU_LTS value based on distribution release
      ansible.builtin.set_fact:
        ubuntu_lts: "{{ ubuntu_lts_mapping[ansible_distribution_release] | default('jammy') }}"
      when: ansible_os_family == 'Debian'

    - name: Add OpenZiti repo (Debian)
      ansible.builtin.deb822_repository:
        components: main
        name: openziti
        signed_by: https://get.openziti.io/tun/package-repos.gpg
        suites: "{{ ubuntu_lts }}"
        state: present
        types: deb
        uris: https://packages.openziti.org/zitipax-openziti-deb-stable
      become: true
      when: ansible_os_family == 'Debian'

    - name: Add OpenZiti repo (RHEL)
      ansible.builtin.yum_repository:
        baseurl: "https://packages.openziti.org/zitipax-openziti-rpm-stable/redhat$releasever/$basearch"
        description: OpenZiti
        enabled: true
        gpgcheck: false
        gpgkey: "https://packages.openziti.org/zitipax-openziti-rpm-stable/redhat$releasever/$basearch/repodata/repomd.xml.key"
        name: OpenZiti
        repo_gpgcheck: true
      become: true
      when: ansible_os_family == 'RedHat'

    - name: Install ziti-edge-tunnel
      ansible.builtin.package:
        name:
          - ziti-edge-tunnel
        state: "present"
      become: true

    - name: Enable + start ziti-edge-tunnel service
      ansible.builtin.systemd_service:
        enabled: true
        name: ziti-edge-tunnel.service
        state: "started"
      become: true

    - name: Define identity name
      ansible.builtin.set_fact:
        ziti_identity_name_fix: "{{ ziti_identity_name | default(ansible_hostname) }}"

    - name: Check if identity is already imported
      ansible.builtin.stat:
        path: "{{ ziti_identity_dir }}/{{ ziti_identity_name_fix }}.json"
      become: true
      register: ziti_identity_import_check

    - name: Add identity
      ansible.builtin.command:
        cmd: 'ziti-edge-tunnel add --jwt "{{ ziti_enroll_token }}" --identity {{ ziti_identity_name_fix }}'
      become: true
      when: not ziti_identity_import_check.stat.exists

    # STEP 2 - CONFIGURE SYSTEM-RESOLVED
    # OpenZiti docs: https://netfoundry.io/docs/openziti/how-to-guides/tunnelers/linux/redhat-package
    # systemd-resolved setup: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/configuring_and_managing_networking/using-different-dns-servers-for-different-domains_configuring-and-managing-networking
    - name: Gather service facts
      ansible.builtin.service_facts:
      when: "ziti_use_systemd_resolved | default(false)"

    - name: Configure systemd-resolved for resolving OpenZiti service names
      block:
      - name: Install systemd-resolved
        ansible.builtin.package:
          name:
            - systemd-resolved
          state: "present"
        become: true

      - name: Enable + start systemd-resolved
        ansible.builtin.systemd_service:
          enabled: true
          name: systemd-resolved
          state: "started"
        become: true

      # Requirement: ansible-galaxy collection install community.general
      - name: Adjust NetworkManager config
        community.general.ini_file:
          no_extra_spaces: true
          option: dns
          path: /etc/NetworkManager/NetworkManager.conf
          section: main
          state: present
          value: systemd-resolved
        become: true
        register: networkmanager_result

      - name: Create symlink
        ansible.builtin.file:
          force: true
          path: /etc/resolv.conf
          src: /run/systemd/resolve/stub-resolv.conf
          state: link
        become: true

      - name: Reload NetworkManager
        ansible.builtin.systemd_service:
          name: NetworkManager
          state: "reloaded"
        become: true
        when: networkmanager_result.changed

      - name: Restart ziti-edge-tunnel # maybe prevents need for reboot
        ansible.builtin.systemd_service:
          name: ziti-edge-tunnel
          state: "restarted"
        become: true

      - name: Get resolvectl status
        ansible.builtin.command:
          cmd: resolvectl status
        register: resolvectl_status
        changed_when: false

      - name: Reboot if ziti nameserver missing in resolvectl status
        ansible.builtin.reboot:
        become: true
        when: "'100.64.0.2' not in resolvectl_status.stdout" # Default nameserver IP of ziti-edge-tunnel is 100.64.0.2

      when:
        - "ziti_use_systemd_resolved | default(false)"
        - "'NetworkManager.service' in services"
        - "services['NetworkManager.service'].state == 'running'"