# Forgejo Runner Setup
# Create new runner via administrator settings inside of forgejo: https://<FORGEJO-URL>/admin/actions/runners/new
# After creation your UUID and token is shown; insert those inside your ansible vars (below at "vars" or inside your inventory file)

- name: Deploy Forgejo runner
  hosts:
    - your_servers
  become: true
  become_user: "{{ podman_user }}"
  gather_facts: false
  vars:
    #podman_user: podman-user
    certs_dir: /app/forgejo-runner/certs
    data_dir: /app/forgejo-runner/data
    # forgejo:
    #   url: https://<FORGEJO-URL>/
    #   uuid: <YOUR-UUID>
    #   token: <YOUR-TOKEN>

# DIND is for security purpose and should be used (https://forgejo.org/docs/latest/admin/actions/docker-access/#docker-in-docker)

  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: '{{ podman_user }}'
        group: '{{ podman_user }}'
        mode: "775"
      loop:
        - '{{ certs_dir }}'
        - '{{ data_dir }}'

    - name: Get user id of podman_user
      ansible.builtin.getent:
        database: passwd
        key: "{{ podman_user }}"
      register: podman_user_info

    - name: Create podman network
      containers.podman.podman_network:
        name: forgejo-runner
        recreate: false

    - name: Remove existing runner container # to prevent dependency issues
      containers.podman.podman_container:
        name: forgejo-runner
        state: absent

    - name: Docker in Podman
      containers.podman.podman_container:
        command: "dockerd -H tcp://0.0.0.0:2375 --tls=false"
        image: docker.io/docker:dind
        name: docker-dind
        network: forgejo-runner
        privileged: true # required for rootless podman
        recreate: false
        restart_policy: always
        state: started
        timezone: Europe/Zurich
        volume:
          - "{{ certs_dir }}:/certs:z"

    - name: Create forgejo runner config file
      ansible.builtin.template:
        src: ./runner/config.yml
        dest: "{{ data_dir }}/config.yml"
        owner: '{{ podman_user }}'
        group: '{{ podman_user }}'

    - name: Forgjeo runner
      containers.podman.podman_container:
        command:
          - "forgejo-runner"
          - "daemon"
          - "--config"
          - "config.yml"
        env:
          DOCKER_HOST: tcp://docker-dind:2375
          DOCKER_CERT_PATH: /certs/client
          DOCKER_TLS_VERIFY: "1"
        image: data.forgejo.org/forgejo/runner:12
        name: forgejo-runner
        network: forgejo-runner
        recreate: false
        requires:
          - docker-dind
        restart_policy: always
        state: started
        timezone: Europe/Zurich
        user: "{{ podman_user_info.ansible_facts.getent_passwd[podman_user][1] }}:{{ podman_user_info.ansible_facts.getent_passwd[podman_user][2] }}"
        userns: keep-id
        volume:
          - "{{ certs_dir }}:/certs:z"
          - "{{ data_dir }}:/data:z"


# Sources/Links
# - https://code.forgejo.org/forgejo/runner/src/branch/main/examples/docker-compose/compose-forgejo-and-runner.yml
# - https://forgejo.org/docs/latest/admin/actions/docker-access/
# - https://forgejo.org/docs/latest/admin/actions/#oci-image-installation
# - https://forgejo.org/docs/latest/admin/actions/installation/docker/
# - https://forgejo.org/docs/latest/admin/actions/security/